services:
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./src:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://host.docker.internal:8000
      - API_URL_CLIENT=http://localhost:8000
      - API_URL_SERVER=http://host.docker.internal:8000
    command: sh -c "npm install && npm run dev"
volumes:
  nuxt_node_modules:
